=== HTMLBook

本をHTMLで執筆しましょう！　HTMLBookはオープンで、XHTML5ベースでプリントとデジタル双方の本を執筆・制作するための標準です。 HTMLBookは以下のような前提で作られています。

* 本は不朽のものです。通常の"本"の構造は100年続いており、そしてデジタルまたは印刷物のかたちで我々の生涯続くでしょう。
* HTMLは近い将来のための世界のマークアップ言語です。
* ワンソースのドキュメント処理は近い将来のために価値があり、存続するでしょう。

HTMLBook自体は以下のように特徴づけられています:

* HTMLBookはXHTML5のサブセットである。すべてのHTMLBookはXHTML5であるが、すべてのXHTML5がHTMLBookであるわけではない。
* HTMLBookはXHTML5仕様にはない追加の要素や属性を含まない。
* HTMLBookは、技術的ドキュメントまたはリファレンスドキュメントで使用されるより複雑なコンテンツも含め、意味的に本の構造にあわせてある。
* HTMLBookはXMLスキーマで定義されており、XMLスキーマで妥当性を検証できる。
* HTMLBookのスタイルシートはCSSで記述されている。

=== HTMLBookを始める

ここにあるHTMLBook仕様のワーキングドラフトを読んでください:

https://github.com/oreillymedia/HTMLBook/blob/master/specification.asciidoc

（訳注: 日本語訳は https://github.com/JAGAT-XML-publishing-study-group/HTMLBook-JA/blob/master/specification.asciidoc ）

ここからHTMLBookスキーマを入手してください:

https://github.com/oreillymedia/HTMLBook/tree/master/schema

HTMLBookのメインスキーマファイルは +htmlbook.xsd+, です、これはMathMLおよびSVGの妥当性を検証するための（W3Cによる）スキーマをインポートしています。

HTMLドキュメントは、 +htmlbook.xsd+ で、コマンドラインで +xmllint+ を使うことにより妥当性を検証できます:

----
$ xmllint --noout --schema htmlbook.xsd <your_html_filename>.html
----

代替手段として、oXygenのようなGUI XMLエディタで妥当性を検証するためには、次のようにルート +<html>+ 要素に +xsi:schemaLocation+ 宣言を追加してください:


----
<html xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://www.w3.org/1999/xhtml ../schema/htmlbook.xsd"
 xmlns="http://www.w3.org/1999/xhtml">
----

=== HTMLBookに関する注記（原注）

* HTMLBook仕様は現在ワーキングドラフトの過程であり、当分の間開発・改訂され続けます。

* HTMLBookについてバグや機能の要望があれば、GitHubのIssuesタブを通じて投稿してください。

* 来月、本をHTMLBookでオーサリングおよび制作するための付属ツールをHTMLBookプロジェクトに追加します:CSSスタイルシート、EPUB/Mobiを生成するためのスクリプト、そのほか。

* HTMLBookプロジェクトに貢献したければ、プルリクエストを送ってください！
